version: '3.8'

services:
  api:
    env_file:
      - .env.dev
    build: .
    depends_on:
      - db
    networks:
      - default
    ports:
      - 5000:5000
    restart: always

  db:
    env_file:
      - .env.dev
    image: postgres:latest
    command: postgres -c stats_temp_directory=/tmp
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  nginx:
    build: ./nginx/
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  postgres-data: