version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env.dev
    environment:
      - ENV=test
    command: >
      bash -c "sh tests-statistics.sh && echo 'This completed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'"
volumes:
  .: